export type ThemeMode = 'default' | 'nordic' | 'forest' | 'biophilic' | 'inema-light' | 'inema-forest' | 'vizora-blue' | 'vizora-green';

export interface ThemeConfig {
  id: ThemeMode;
  name: string;
  shortName: string;
  badge: string;
  description: string;
  path: string;
  solidFirstKpi?: boolean;
  tokens: {
    canvasBg: string;
    sidebarBg: string;
    sidebarBorder: string;
    sidebarText: string;
    sidebarTextMuted: string;
    sidebarTextActive: string;
    sidebarPillActive: string;
    sidebarBorderActive: string;
    sidebarHover: string;
    sidebarIndicator?: string;
    headerBg: string;
    headerBorder: string;
    cardBg: string;
    cardBorder: string;
    cardShadow: string;
    brandPrimary: string;
    brandPrimaryHover: string;
    brandText: string;
    accentPillBg: string;
    accentPillText: string;
    accentPillBorder: string;
    chartColors: {
      primary: string;
      secondary: string;
      tertiary: string;
      quaternary: string;
      muted: string;
    };
  };
}

export const THEMES: Record<ThemeMode, ThemeConfig> = {
  default: {
    id: 'default',
    name: 'Opção 1: Sidebar Azul Petróleo (#0c4353)',
    shortName: '01. Azul Petróleo',
    badge: 'Recursos Hídricos',
    description: 'Sidebar em Azul Petróleo Oceânico (#0c4353), logotipo oficial nítido em branco, gráficos vibrantes (#78C043 e #005ea3) e botões no Azul Institucional.',
    path: '/',
    solidFirstKpi: false,
    tokens: {
      canvasBg: 'bg-slate-50',
      sidebarBg: 'bg-[#0c4353]',
      sidebarBorder: 'border-[#145366]',
      sidebarText: 'text-[#9ec3cc]',
      sidebarTextMuted: 'text-[#7ea8b3]',
      sidebarTextActive: 'text-white',
      sidebarPillActive: 'bg-[#165a6e]',
      sidebarBorderActive: 'border border-[#207087]',
      sidebarHover: 'hover:bg-[#135467] hover:text-white',
      sidebarIndicator: '#34D399',
      headerBg: 'bg-white',
      headerBorder: 'border-slate-200',
      cardBg: 'bg-white',
      cardBorder: 'border-slate-200/70',
      cardShadow: 'shadow-2xs',
      brandPrimary: 'bg-blue-600',
      brandPrimaryHover: 'hover:bg-blue-700',
      brandText: 'text-slate-900',
      accentPillBg: 'bg-green-50',
      accentPillText: 'text-green-700',
      accentPillBorder: 'border-green-200/70',
      chartColors: {
        primary: '#78C043',
        secondary: '#005ea3',
        tertiary: '#5e9c31',
        quaternary: '#0073C4',
        muted: '#94a3b8',
      },
    },
  },
  nordic: {
    id: 'nordic',
    name: 'Caminho 01: Nordic Climate Tech',
    shortName: '01. Nordic',
    badge: 'Watershed',
    description: 'Fundo off-white com temperatura sálvia sutil, bordas botânicas e alta precisão editorial.',
    path: '/conceito-01',
    tokens: {
      canvasBg: 'bg-[#F7F9F8]',
      sidebarBg: 'bg-[#FCFDFD]',
      sidebarBorder: 'border-[#E1ECE6]',
      sidebarText: 'text-[#2D3F37]',
      sidebarTextMuted: 'text-[#5B7368]',
      sidebarTextActive: 'text-[#0B3B2C]',
      sidebarPillActive: 'bg-[#E8F3EE]',
      sidebarBorderActive: 'border-[#CBDED8]',
      sidebarHover: 'hover:bg-[#F2F6F4]',
      headerBg: 'bg-[#FCFDFD]',
      headerBorder: 'border-[#E1ECE6]',
      cardBg: 'bg-white',
      cardBorder: 'border-[#E1ECE6]',
      cardShadow: 'shadow-[0_1px_3px_rgba(11,59,44,0.04)]',
      brandPrimary: 'bg-[#0B3B2C]',
      brandPrimaryHover: 'hover:bg-[#082a20]',
      brandText: 'text-[#0B3B2C]',
      accentPillBg: 'bg-[#E8F3EE]',
      accentPillText: 'text-[#0F5A42]',
      accentPillBorder: 'border-[#D2E7DC]',
      chartColors: {
        primary: '#0B3B2C',
        secondary: '#105C45',
        tertiary: '#3F886E',
        quaternary: '#7AB89F',
        muted: '#A5C2B5',
      },
    },
  },
  forest: {
    id: 'forest',
    name: 'Caminho 02: Institutional Deep Forest',
    shortName: '02. Deep Forest',
    badge: 'Linear',
    description: 'Sidebar em Verde Floresta Obsidiana (#0A221A), contraste de alta patente e miolo luminoso.',
    path: '/conceito-02',
    tokens: {
      canvasBg: 'bg-[#F8FAFA]',
      sidebarBg: 'bg-[#0A221A]',
      sidebarBorder: 'border-[#143B2E]',
      sidebarText: 'text-[#E0ECE7]',
      sidebarTextMuted: 'text-[#8EA89F]',
      sidebarTextActive: 'text-white',
      sidebarPillActive: 'bg-[#144233]',
      sidebarBorderActive: 'border-[#21614C]',
      sidebarHover: 'hover:bg-[#12362A]',
      sidebarIndicator: '#34D399',
      headerBg: 'bg-white',
      headerBorder: 'border-slate-200/90',
      cardBg: 'bg-white',
      cardBorder: 'border-slate-200',
      cardShadow: 'shadow-xs',
      brandPrimary: 'bg-[#0F5A42]',
      brandPrimaryHover: 'hover:bg-[#0a402e]',
      brandText: 'text-slate-900',
      accentPillBg: 'bg-[#E8F5F1]',
      accentPillText: 'text-[#0A543E]',
      accentPillBorder: 'border-[#C2E8DC]',
      chartColors: {
        primary: '#0F5A42',
        secondary: '#10B981',
        tertiary: '#34D399',
        quaternary: '#6EE7B7',
        muted: '#94A3B8',
      },
    },
  },
  biophilic: {
    id: 'biophilic',
    name: 'Caminho 03: Biophilic Mineral Tech',
    shortName: '03. Mineral',
    badge: 'Ramp',
    description: 'Calor orgânico em Mineral Oat (#F5F6F2), pedra mineral polida e Verde Musgo Cipreste (#153E32).',
    path: '/conceito-03',
    tokens: {
      canvasBg: 'bg-[#F5F6F2]',
      sidebarBg: 'bg-[#FAFBF8]',
      sidebarBorder: 'border-[#E3E7DE]',
      sidebarText: 'text-[#2A352F]',
      sidebarTextMuted: 'text-[#6B756D]',
      sidebarTextActive: 'text-[#153E32]',
      sidebarPillActive: 'bg-[#EAEFE8]',
      sidebarBorderActive: 'border-[#D5DDD2]',
      sidebarHover: 'hover:bg-[#F2F5F0]',
      headerBg: 'bg-[#FAFBF8]',
      headerBorder: 'border-[#E3E7DE]',
      cardBg: 'bg-white',
      cardBorder: 'border-[#E3E7DE]',
      cardShadow: 'shadow-xs',
      brandPrimary: 'bg-[#153E32]',
      brandPrimaryHover: 'hover:bg-[#0e2c23]',
      brandText: 'text-[#153E32]',
      accentPillBg: 'bg-[#EBF0E8]',
      accentPillText: 'text-[#1D5444]',
      accentPillBorder: 'border-[#D8E2D4]',
      chartColors: {
        primary: '#153E32',
        secondary: '#285A48',
        tertiary: '#487A68',
        quaternary: '#739F8F',
        muted: '#A8BFB5',
      },
    },
  },
  'inema-light': {
    id: 'inema-light',
    name: 'Opção 3: Sidebar Branca Institucional',
    shortName: '03. Sidebar Branca',
    badge: 'Clean / Light',
    description: 'Sidebar branca com logotipo oficial colorido em alta definição, alto contraste, visual arejado e botões azuis.',
    path: '/proposta-branca',
    solidFirstKpi: false,
    tokens: {
      canvasBg: 'bg-slate-50',
      sidebarBg: 'bg-white',
      sidebarBorder: 'border-slate-200',
      sidebarText: 'text-slate-600',
      sidebarTextMuted: 'text-slate-400',
      sidebarTextActive: 'text-blue-800',
      sidebarPillActive: 'bg-blue-50',
      sidebarBorderActive: 'border-l-4 border-blue-600',
      sidebarHover: 'hover:bg-slate-100/80 hover:text-slate-900',
      sidebarIndicator: '#005ea3',
      headerBg: 'bg-white',
      headerBorder: 'border-slate-200',
      cardBg: 'bg-white',
      cardBorder: 'border-slate-200/70',
      cardShadow: 'shadow-2xs',
      brandPrimary: 'bg-blue-600',
      brandPrimaryHover: 'hover:bg-blue-700',
      brandText: 'text-slate-900',
      accentPillBg: 'bg-green-50',
      accentPillText: 'text-green-700',
      accentPillBorder: 'border-green-200',
      chartColors: {
        primary: '#78C043',
        secondary: '#005ea3',
        tertiary: '#5e9c31',
        quaternary: '#0073C4',
        muted: '#94a3b8',
      },
    },
  },
  'inema-forest': {
    id: 'inema-forest',
    name: 'Tema 2: Dark Forest Sidebar',
    shortName: '02. Dark Forest',
    badge: 'INEMA Forest',
    description: 'Sidebar escura em bg-forest-900 sem borda, itens ativos em bg-white/10, cards brancos leves e acentos Verde Vibrante (#78C043).',
    path: '/proposta-02',
    solidFirstKpi: false,
    tokens: {
      canvasBg: 'bg-slate-50',
      sidebarBg: 'bg-forest-900',
      sidebarBorder: 'border-transparent border-r-0',
      sidebarText: 'text-slate-400',
      sidebarTextMuted: 'text-slate-400',
      sidebarTextActive: 'text-white',
      sidebarPillActive: 'bg-white/10',
      sidebarBorderActive: 'border-transparent',
      sidebarHover: 'hover:bg-white/5 hover:text-white',
      sidebarIndicator: '#78C043',
      headerBg: 'bg-white',
      headerBorder: 'border-slate-200',
      cardBg: 'bg-white',
      cardBorder: 'border-slate-200/60',
      cardShadow: 'shadow-2xs',
      brandPrimary: 'bg-blue-600',
      brandPrimaryHover: 'hover:bg-blue-700',
      brandText: 'text-slate-900',
      accentPillBg: 'bg-green-50',
      accentPillText: 'text-green-700',
      accentPillBorder: 'border-green-200',
      chartColors: {
        primary: '#78C043',
        secondary: '#005ea3',
        tertiary: '#5e9c31',
        quaternary: '#0073C4',
        muted: '#94a3b8',
      },
    },
  },
  'vizora-blue': {
    id: 'vizora-blue',
    name: 'Sidebar Azul Petróleo (#0c4353) + Botões Azuis',
    shortName: 'Petróleo + Azul',
    badge: 'IDV Oficial',
    description: 'Sidebar em Azul Petróleo Oceânico (#0c4353), logotipo oficial nítido em branco, gráficos vibrantes (#78C043 e #005ea3), botões no Azul Institucional e assistente em gradiente.',
    path: '/proposta-verde-azul',
    solidFirstKpi: false,
    tokens: {
      canvasBg: 'bg-slate-50',
      sidebarBg: 'bg-[#0c4353]',
      sidebarBorder: 'border-[#145366]',
      sidebarText: 'text-[#9ec3cc]',
      sidebarTextMuted: 'text-[#7ea8b3]',
      sidebarTextActive: 'text-white',
      sidebarPillActive: 'bg-[#165a6e]',
      sidebarBorderActive: 'border border-[#207087]',
      sidebarHover: 'hover:bg-[#135467] hover:text-white',
      sidebarIndicator: '#34D399',
      headerBg: 'bg-white',
      headerBorder: 'border-slate-200',
      cardBg: 'bg-white',
      cardBorder: 'border-slate-200/70',
      cardShadow: 'shadow-2xs',
      brandPrimary: 'bg-blue-600',
      brandPrimaryHover: 'hover:bg-blue-700',
      brandText: 'text-slate-900',
      accentPillBg: 'bg-green-50',
      accentPillText: 'text-green-700',
      accentPillBorder: 'border-green-200/70',
      chartColors: {
        primary: '#78C043',
        secondary: '#005ea3',
        tertiary: '#5e9c31',
        quaternary: '#0073C4',
        muted: '#94a3b8',
      },
    },
  },
  'vizora-green': {
    id: 'vizora-green',
    name: 'Opção 2: Sidebar Verde Refinado (#185846)',
    shortName: '02. Verde Refinado',
    badge: 'Meio Ambiente',
    description: 'Sidebar em Verde Refinado (#185846) com tom botânico agradável (não muito escuro), logotipo branco nítido, botões no Azul Institucional e gráficos vibrantes.',
    path: '/proposta-verde',
    solidFirstKpi: false,
    tokens: {
      canvasBg: 'bg-slate-50',
      sidebarBg: 'bg-[#185846]',
      sidebarBorder: 'border-[#206954]',
      sidebarText: 'text-[#bce0d3]',
      sidebarTextMuted: 'text-[#97c7b6]',
      sidebarTextActive: 'text-white',
      sidebarPillActive: 'bg-[#22725b]',
      sidebarBorderActive: 'border border-[#2c8d71]',
      sidebarHover: 'hover:bg-[#1f6853] hover:text-white',
      sidebarIndicator: '#34D399',
      headerBg: 'bg-white',
      headerBorder: 'border-slate-200',
      cardBg: 'bg-white',
      cardBorder: 'border-slate-200/70',
      cardShadow: 'shadow-2xs',
      brandPrimary: 'bg-blue-600',
      brandPrimaryHover: 'hover:bg-blue-700',
      brandText: 'text-slate-900',
      accentPillBg: 'bg-green-50',
      accentPillText: 'text-green-700',
      accentPillBorder: 'border-green-200/70',
      chartColors: {
        primary: '#78C043',
        secondary: '#005ea3',
        tertiary: '#5e9c31',
        quaternary: '#0073C4',
        muted: '#94a3b8',
      },
    },
  },
};
